- name: Install all packages
  hosts: webservers
  vars:
    gen_by_an: Ansible
    django_site: denis
    django_engine_db: mysql
  user: root
  sudo: no
  roles:
    - common
    - mysql
    - django
    - httpd
