- name: Install all packages
  hosts: webservers
  vars:
    gen_by_an: Ansible
  user: root
  sudo: no
  tasks: 
    - name: Install libselinux-python
      yum: name=libselinux-python state=present  
  roles:
    - mysql
    - httpd
