- name: Install all packages
  hosts: webservers
  vars:
    gen_by_an: Ansible
    django_site: denis
    django_engine_db: mysql
    apps: 
       search: 
          git_url: git@git.epam.com:mikhail_mikhalap/ansible-centos6-6.git
  user: root
  sudo: no
  roles:
    - common
    - mysql
    - django
    - httpd
