---
 - name: Install mysql server
   yum: name=mysql-server state=present
 - name: Install mysql client 
   yum: name=mysql state=present
 - name: Start mysqld
   service: name=mysqld state=started
 
