---
 - name: Install django
   pip: name=django
 - name: Install mysql-connector
   pip: name=mysqlclient
 - script: t.sh {{ django_site }} {{ log_file }}
 - script: deploy_apps.sh {{ django_site }} {{ item.key }} {{ item.value.git_url }} {{ log_file }}
   with_dict: "{{ apps }}"
   tags:
     - deploy_apps
 - name: Configure django
   template: src=settings.py.j2 dest={{django_site}}/{{django_site}}/settings.py
