---
 - name: Install django
   pip: name=django
 - name: Install mysql-connector
   apt: name=python-mysql.connector state=present
 - script: t.sh {{ django_site }}
 - name: Configure django
   template: src=settings.py.j2 dest={{django_site}}/{{django_site}}/settings.py
