---
 - name: Install httpd
   apt: name=httpd state=present
   notify:
    - start httpd
 - name: httpd.conf
   copy: src=httpd.conf dest=/etc/httpd/conf/httpd.conf
   notify:
    - restart httpd
 - name: Create files
   copy: src=Sudoku_free.jar dest=/var/www/html/Sudoku_free.jar
 - name: Templates   
   template: src=t.f.j2 dest=/var/www/html/index.html
