---
 - name: Apt-get update
   apt: name=update_cache
 - name: Install common packages
   apt: name={{ item }} state=present
   with_items:
      - python-pip
      - python-dev
      - libmysqld-dev
